listen_addr: ":8082"
backend_api_url: "http://localhost:8080"
backend_api_key: "your-secret-key-12345"
proxy_bin_path: "./bin/reolinkproxy"
proxy_base_rtsp_port: 8554
proxy_base_onvif_port: 8002
device_status_interval_sec: 60
dahua:
  python_path: "/usr/bin/python3"
  script_path: "/opt/dh-p2p/main.py"

xiongmai:
  node_path: "/usr/bin/node"
  script_path: "/opt/xmeye-proxy/index.js"