listen_addr: ":8082"
backend_api_url: "http://localhost:8080"
backend_api_key: "your-secret-key"
proxy_base_rtsp_port: 8554
proxy_base_onvif_port: 8002
device_status_interval_sec: 60

#Reolink
proxy_bin_path: "./bin/neolink"


# Hikvision
hikvision_username: "your_email@example.com"
hikvision_password: "your_password"
ffmpeg_path: "/usr/bin/ffmpeg"

# Dahua
dahua_python_path: "/usr/bin/python3"
dahua_script_path: "./bin/dh-p2p/main.py"

# Xiongmai
xiongmai_node_path: "/usr/bin/node"
xiongmai_script_path: "/opt/xmeye-proxy/index.js"