// ═══════════════════════════════════════════════════════════════════════
// Centralized Icon Exports
// P1-OPT.1: Единая точка входа для всех иконок lucide-react.
// Гарантирует tree-shaking — Rollup видит только используемые иконки.
// ═══════════════════════════════════════════════════════════════════════

export {
  Activity,
  AlertCircle,
  AlertOctagon,
  AlertTriangle,
  ArrowLeft,
  ArrowRight,
  BarChart3,
  Bell,
  BookOpen,
  Briefcase,
  Calendar,
  CalendarClock,
  CalendarDays,
  Camera,
  Check,
  CheckCircle,
  ChevronDown,
  ChevronLeft,
  ChevronRight,
  ChevronUp,
  ChevronsUpDown,
  ClipboardList,
  Clock,
  Code,
  Columns,
  Command,
  Copy,
  Database,
  DollarSign,
  Download,
  Edit,
  Edit2,
  Edit3,
  ExternalLink,
  Eye,
  EyeOff,
  File,
  FileSpreadsheet,
  FileText,
  Film,
  Filter,
  Gauge,
  Globe,
  GripVertical,
  HardDrive,
  Home,
  Hourglass,
  Image,
  Info,
  Key,
  Keyboard,
  LayoutDashboard,
  Link,
  List,
  Loader,
  Loader2,
  Lock,
  LogOut,
  Mail,
  MapPin,
  MessageCircle,
  Monitor,
  Moon,
  MoreVertical,
  MoveDown,
  MoveLeft,
  MoveRight,
  MoveUp,
  Package,
  Palette,
  Pause,
  Play,
  Plus,
  Printer,
  Receipt,
  RefreshCw,
  RotateCcw,
  Save,
  Search,
  Send,
  Server,
  Settings,
  Share2,
  Shield,
  ShieldCheck,
  Smartphone,
  Sun,
  Table2,
  Ticket,
  Trash2,
  TrendingDown,
  TrendingUp,
  Unlock,
  Upload,
  User,
  Users,
  Wifi,
  WifiOff,
  Wrench,
  X,
  XCircle,
  Zap,
  ZoomIn,
  ZoomOut,
} from 'lucide-react';

// ── Aliased re-exports ─────────────────────────────────────────────────
export { Settings as SettingsIcon, User as UserIcon } from 'lucide-react';

// ── Type re-exports ────────────────────────────────────────────────────
export type { LucideIcon } from 'lucide-react';
