// Package purchase — Purchase Orders (INV-7.3.x).
//
// INV-7.3.1: PurchaseOrder entity + PO Line Items
// INV-7.3.2: PO Line Items с привязкой к Part
// INV-7.3.3: Auto-PO при low-stock
// INV-7.3.4: Goods Receipt
package purchase

import (
	"fmt"
	"time"
)

// ═══════════════════════════════════════════════════════════════════════
// INV-7.3.1: PurchaseOrder entity
// ═══════════════════════════════════════════════════════════════════════

type POStatus string

const (
	PODraft    POStatus = "DRAFT"
	POSent     POStatus = "SENT"
	POApproved POStatus = "APPROVED"
	POReceived POStatus = "RECEIVED"
	POClosed   POStatus = "CLOSED"
	POCancelled POStatus = "CANCELLED"
)

type PurchaseOrder struct {
	ID              string        `json:"id" db:"id"`
	PONumber        string        `json:"po_number" db:"po_number"` // auto-generated: PO-2026-0001
	VendorID        string        `json:"vendor_id" db:"vendor_id"`
	VendorName      string        `json:"vendor_name,omitempty" db:"-"`
	Status          POStatus      `json:"status" db:"status"`
	LineItems       []POLineItem  `json:"line_items" db:"line_items"`
	Subtotal        float64       `json:"subtotal" db:"subtotal"`
	Tax             float64       `json:"tax" db:"tax"`
	Total           float64       `json:"total" db:"total"`
	Currency        string        `json:"currency" db:"currency"` // ISO 4217
	Notes           string        `json:"notes,omitempty" db:"notes"`
	CreatedBy       string        `json:"created_by" db:"created_by"`
	ApprovedBy      *string       `json:"approved_by,omitempty" db:"approved_by"`
	ApprovedAt      *time.Time    `json:"approved_at,omitempty" db:"approved_at"`
	ExpectedDate    *time.Time    `json:"expected_date,omitempty" db:"expected_date"`
	ReceivedDate    *time.Time    `json:"received_date,omitempty" db:"received_date"`
	AutoGenerated   bool          `json:"auto_generated" db:"auto_generated"` // from low-stock trigger
	CreatedAt       time.Time     `json:"created_at" db:"created_at"`
	UpdatedAt       time.Time     `json:"updated_at" db:"updated_at"`
}

// ═══════════════════════════════════════════════════════════════════════
// INV-7.3.2: PO Line Items
// ═══════════════════════════════════════════════════════════════════════

type POLineItem struct {
	ID         string  `json:"id" db:"id"`
	POID       string  `json:"po_id" db:"po_id"`
	PartID     string  `json:"part_id" db:"part_id"`
	PartName   string  `json:"part_name,omitempty" db:"-"`
	PartSKU    string  `json:"part_sku,omitempty" db:"-"`
	Quantity   int     `json:"quantity" db:"quantity" validate:"required,min=1"`
	UnitPrice  float64 `json:"unit_price" db:"unit_price" validate:"required,min=0"`
	TotalPrice float64 `json:"total_price" db:"total_price"` // quantity × unit_price
}

// ═══════════════════════════════════════════════════════════════════════
// INV-7.3.4: Goods Receipt
// ═══════════════════════════════════════════════════════════════════════

type GoodsReceipt struct {
	ID          string              `json:"id" db:"id"`
	POID        string              `json:"po_id" db:"po_id"`
	ReceivedBy  string              `json:"received_by" db:"received_by"`
	ReceivedAt  time.Time           `json:"received_at" db:"received_at"`
	Items       []GoodsReceiptItem  `json:"items" db:"items"`
	Notes       string              `json:"notes,omitempty" db:"notes"`
}

type GoodsReceiptItem struct {
	LineItemID  string `json:"line_item_id" db:"line_item_id"`
	PartID      string `json:"part_id" db:"part_id"`
	ExpectedQty int    `json:"expected_qty" db:"expected_qty"`
	ReceivedQty int    `json:"received_qty" db:"received_qty"`
	DamagedQty  int    `json:"damaged_qty" db:"damaged_qty"`
	Accepted    bool   `json:"accepted" db:"accepted"`
}

// ═══════════════════════════════════════════════════════════════════════
// Auto-PO Engine (INV-7.3.3)
// ═══════════════════════════════════════════════════════════════════════

type AutoPOConfig struct {
	MinStockThreshold int     // % of min_stock that triggers auto-PO (e.g., 50 = 50%)
	DefaultQuantity   int     // default order quantity
	DefaultVendorID   string  // fallback vendor
	Currency          string  // default currency
}

func DefaultAutoPOConfig() AutoPOConfig {
	return AutoPOConfig{
		MinStockThreshold: 50,
		DefaultQuantity:   10,
		DefaultVendorID:   "",
		Currency:          "USD",
	}
}

// AutoPOTrigger содержит информацию для автоматического создания PO.
type AutoPOTrigger struct {
	PartID      string  `json:"part_id"`
	PartName    string  `json:"part_name"`
	PartSKU     string  `json:"part_sku"`
	CurrentStock int    `json:"current_stock"`
	MinStock    int     `json:"min_stock"`
	SuggestedQty int    `json:"suggested_quantity"`
	UnitPrice   float64 `json:"unit_price"`
	VendorID    string  `json:"vendor_id,omitempty"`
}

// CheckLowStock проверяет, нужно ли создавать PO для запчасти.
func CheckLowStock(currentStock, minStock int, config AutoPOConfig) *AutoPOTrigger {
	if minStock <= 0 {
		return nil
	}

	threshold := int(float64(minStock) * float64(config.MinStockThreshold) / 100.0)
	if currentStock <= threshold {
		suggestedQty := config.DefaultQuantity
		if suggestedQty <= 0 {
			suggestedQty = minStock * 2
		}
		return &AutoPOTrigger{
			CurrentStock:  currentStock,
			MinStock:      minStock,
			SuggestedQty:  suggestedQty,
		}
	}
	return nil
}

// GeneratePONumber генерирует номер PO.
func GeneratePONumber(year int, seq int) string {
	return fmt.Sprintf("PO-%d-%04d", year, seq)
}

// CalculateLineTotal вычисляет общую сумму позиции.
func (item *POLineItem) CalculateLineTotal() {
	item.TotalPrice = float64(item.Quantity) * item.UnitPrice
}

// CalculateTotals пересчитывает суммы PO.
func (po *PurchaseOrder) CalculateTotals() {
	po.Subtotal = 0
	for i := range po.LineItems {
		po.LineItems[i].CalculateLineTotal()
		po.Subtotal += po.LineItems[i].TotalPrice
	}
	po.Total = po.Subtotal + po.Tax
}

// Summary возвращает краткую сводку по PO.
func (po *PurchaseOrder) Summary() string {
	return fmt.Sprintf("%s [%s] %s: $%.2f (%d items)",
		po.PONumber, po.Status, po.VendorName, po.Total, len(po.LineItems))
}
